name: Stylua Format Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lua Format Check
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.17.1
          args: --color always --check .
